apiVersion: apps/v1
kind: Deployment
metadata:
  name: location-service-deployment
  labels:
    app: location-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: location-service
  template:
    metadata:
      labels:
        app: location-service

    spec:
      containers:
        - name: location-service
          image: caiohoffmann/location-service:latest
          ports:
            - containerPort: 4000