apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-deployment
  labels:
    app: orders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders

    spec:
      containers:
        - name: orders
          image: caiohoffmann/orders:latest
          ports:
            - containerPort: 8082