apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurants-service-deployment
  labels:
    app: restaurants-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurants-service
  template:
    metadata:
      labels:
        app: restaurants-service

    spec:
      containers:
        - name: restaurants-service
          image: caiohoffmann/restaurants-service:latest
          ports:
            - containerPort: 8091