server:
  port: 8080
spring:
  kafka:
    producer:
      bootstrap-servers: my-kafka:9092
      key-serializer: com.example.demo.engine.PayloadSerializer
      value-serializer: com.example.demo.engine.PayloadSerializer
