apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gw-deployment
  labels:
    app: api-gw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gw
  template:
    metadata:
      labels:
        app: api-gw

    spec:
      containers:
        - name: api-gw
          image: caiohoffmann/apigw:latest
          ports:
            - containerPort: 8085
          env:
            - name: locationServ
              value: location-service
            - name: locationServPort
              value: '4000'
            - name: userServ
              value: account-service2  
            - name: userServPort
              value: '3000'  
            - name: orderStatuServ
              value: order-status  
            - name: orderStatuServPort
              value: '8097'  
            - name: orderServ
              value: orders
            - name: orderServPort
              value: '8082'   
            - name: restaurantServ
              value: restaurants-service 
            - name: restaurantServPort
              value: '8091'  
            - name: rankingServ
              value: ranking-service   
            - name: rankingServPort
              value: '8099'  
            - name: paymentServ
              value: ea-wk2-db   
            - name: dealsServ
              value: deals
            - name: dealsServPort
              value: '8094'
            - name: favoriteServ
              value: favorites
            - name: favoriteServPort
              value: "3005"
            - name: jwtSecret
              value: mytopsecret