apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service-deployment
  labels:
    app: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: caiohoffmann/payment-service
        ports:
          - containerPort: 8093
        env:
          - name: KAFKA_SERVER
            valueFrom:
              configMapKeyRef:
              # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
                name: payment-service-config
              # Specify the key associated with the value
                key: kafkaServer
          - name: KAFKA_TOPIC
            valueFrom:
              configMapKeyRef:
              # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
                name: payment-service-config
              # Specify the key associated with the value
                key: kafkaTopic
          - name: MONGODB_HOST
            valueFrom:
              configMapKeyRef:
                name: payment-service-config
                key: mongodb-host
          - name: MONGODB_USER_NAME
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: mongodb-user-name
          - name: MONGODB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: mongodb-password

                  
